In [1]:
import numpy as np

a=np.array([1,5,6,7,9])

b=np.array([2,5,8,7,9])
print(a==b)
print(np.flatnonzero(a==b))
print(np.mean(a==b)) 

print(np.square(a-b[0]))

print(np.sum(np.square(a-b[0])))

[False  True False  True  True]
[1 3 4]
0.6
[ 1  9 16 25 49]
100


In [10]:
classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
num_classes = len(classes)
samples_per_class = 7
for y, cls in enumerate(classes):
    print(y,cls)

0 plane
1 car
2 bird
3 cat
4 deer
5 dog
6 frog
7 horse
8 ship
9 truck


In [65]:
i=np.random.random((5,4))
print(i)


k=np.array_split(i,3,axis=0)
print(k[1])
print(i.remove(k[1]))

[[ 0.07930472  0.12777451  0.11510696  0.3702024 ]
 [ 0.26901598  0.18373956  0.6410127   0.69290064]
 [ 0.24774193  0.35145212  0.57894407  0.57459964]
 [ 0.216374    0.94967008  0.45012655  0.32302187]
 [ 0.30021483  0.00307324  0.18130637  0.75821483]]
[[ 0.24774193  0.35145212  0.57894407  0.57459964]
 [ 0.216374    0.94967008  0.45012655  0.32302187]]


AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [35]:
print(i[1])
print(np.argsort(i[1], axis=0, kind='quicksort', order=None))
print(j[(np.argsort(i[1], axis=0, kind='quicksort', order=None))[0:2]])


[ 0.62496351  0.34175744  0.13151777  0.59982291]
[2 1 3 0]
[ 1.  1.]


In [39]:
def most_common(lst):
    return max(set(lst), key=lst.count)

p=[3,2,5,2,4,4]
print(most_common(p))

2


In [57]:
for i in range(5):
    print(i)

0
1
2
3
4
